/**
 *
 * $Id$
 */
package fr.cnam.chatnoir76.creaturedecombat.model.validation;

import org.eclipse.emf.common.util.EList;

import fr.cnam.chatnoir76.creaturedecombat.model.Attaque;
import fr.cnam.chatnoir76.creaturedecombat.model.Categorie;
import fr.cnam.chatnoir76.creaturedecombat.model.Degat;
import fr.cnam.chatnoir76.creaturedecombat.model.Niveau;

/**
 * A sample validator interface for {@link fr.cnam.chatnoir76.creaturedecombat.model.GenAbstractCreatureComponent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AbstractCreatureComponentValidator {
	boolean validate();

	boolean validatePvInit(int value);
	boolean validateCategorie(Categorie value);
	boolean validateAttaques(EList<Attaque> value);
	boolean validateDegatDefense(Degat value);
	boolean validateNiveau(Niveau value);
}
