/**
 *
 * $Id$
 */
package fr.cnam.chatnoir76.creaturedecombat.model.validation;

import fr.cnam.chatnoir76.creaturedecombat.model.CalculDegat;
import fr.cnam.chatnoir76.creaturedecombat.model.TypeDegat;

/**
 * A sample validator interface for {@link fr.cnam.chatnoir76.creaturedecombat.model.GenDegat}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DegatValidator {
	boolean validate();

	boolean validateId(int value);

	boolean validateType(TypeDegat value);
	boolean validateModeCalcul(CalculDegat value);
	boolean validateDegat(int value);
	boolean validateIncertitude(int value);
	boolean validateChanceRattage(int value);
}
