/**
 *
 * $Id$
 */
package fr.cnam.chatnoir76.creaturedecombat.model.validation;

import org.eclipse.emf.common.util.EList;

import fr.cnam.chatnoir76.creaturedecombat.model.Carte;
import fr.cnam.chatnoir76.creaturedecombat.model.Creature;
import fr.cnam.chatnoir76.creaturedecombat.model.Deck;

/**
 * A sample validator interface for {@link fr.cnam.chatnoir76.creaturedecombat.model.GenJeu}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface JeuValidator {
	boolean validate();

	boolean validateDeck(Deck value);
	boolean validatePileDefausse(EList<Carte> value);
	boolean validateCreatureActive(Creature value);
	boolean validateBanc(EList<Creature> value);
	boolean validateCarteRecompense(EList<Carte> value);
	boolean validateMain(EList<Carte> value);
}
