/**
 *
 * $Id$
 */
package fr.cnam.chatnoir76.creaturedecombat.model.validation;

import fr.cnam.chatnoir76.creaturedecombat.model.Evolution;

/**
 * A sample validator interface for {@link fr.cnam.chatnoir76.creaturedecombat.model.GenMaitre}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MaitreValidator {
	boolean validate();

	boolean validateEvolution(Evolution value);
}
