/**
 *
 * $Id$
 */
package fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.validation;

import fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.CreatureComponent;
import fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.Energie;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.GenCreature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CreatureValidator {
	boolean validate();

	boolean validateEnergies(EList<Energie> value);
	boolean validateBase(CreatureComponent value);
	boolean validateEvolution(CreatureComponent value);
	boolean validateMaitre(CreatureComponent value);
	boolean validatePv(int value);
}
