/**
 *
 * $Id$
 */
package fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.validation;

import fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.Attaque;
import fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.Base;
import fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.Categorie;
import fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.Degat;
import fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.Energie;

import fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.Evolution;
import fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.Maitre;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.GenCreature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CreatureValidator {
	boolean validate();

	boolean validateBase(Base value);
	boolean validateEvolution(Evolution value);

	boolean validateMaitre(Maitre value);

	boolean validatePv(int value);

	boolean validatePvInit(int value);

	boolean validateNom(String value);

	boolean validateDescription(String value);

	boolean validateCategorie(Categorie value);

	boolean validateAttaques(EList<Attaque> value);

	boolean validateDegatDefense(Degat value);

	boolean validateEnergies(EList<Energie> value);
}
