/**
 *
 * $Id$
 */
package fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.validation;

import org.eclipse.emf.common.util.EList;

import fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.Attaque;
import fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.Categorie;
import fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.Creature;
import fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.Degat;
import fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.Energie;

/**
 * A sample validator interface for {@link fr.cnam.chatnoir76.creaturedecombat.domain.creature.model.GenCreature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CreatureValidator {
	boolean validate();

	boolean validateCategorie(Categorie value);
	boolean validatePv(int value);
	boolean validatePvInit(int value);
	boolean validateBase(Creature value);
	boolean validateAttaques(EList<Attaque> value);
	boolean validateEnergies(EList<Energie> value);
	boolean validateDegatDefense(Degat value);
}
